{addons: {apt: {packages: [lib32stdc++6, lib32z1, lib32z1-dev]}}, after_success: coveralls,
  before_cache: ['find build-support -name "*.py[co]" -print -delete', find $HOME/.ivy2/pants
      -type f -name "ivydata-*.properties" -print -delete, 'rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}',
    rm -rf $HOME/.ivy2/pants/com.example, rm -rf $HOME/.cache/pants/stats], before_install: [
    jdk_switcher use oraclejdk8], before_script: './build-support/bin/ci-sync.sh

    ./build-support/bin/install-android-sdk.sh

    ', cache: {directories: [$HOME/.cache/pants, $HOME/.ivy2/pants, $HOME/.npm, $HOME/.android,
      $ANDROID_SDK_INSTALL_LOCATION, build-support/isort.venv, build-support/pants_dev_deps.venv]},
  dist: trusty, env: {global: [ANDROID_SDK_INSTALL_LOCATION="$HOME/opt/android-sdk-install",
      ANDROID_HOME="$ANDROID_SDK_INSTALL_LOCATION/android-sdk-linux", CXX=g++, 'PANTS_CONFIG_OVERRIDE="[''pants.travis-ci.ini'']"',
      {secure: VvwbndU++a2/iNAjk9cd67ATiipDwqcKnxDR4/J2Ik3GH10wHEDUhJ1+MK4WLhedfaOakDOEmarZQS3GwtgvCHO3knpTJuJc8d/bCfZovYuSqdi//BEv4dS7hDt6tQeJfkbBjG0T4yNjPJ3W9R9KDWCy/vj2CUm90BGg2CmxUbg=}],
    matrix: [CI_FLAGS="-fkmsrjlpn -i 1/6 'Python integration tests for pants - shard
        2'", CI_FLAGS="-fkmsrjlpn -i 2/6 'Python integration tests for pants - shard
        3'", CI_FLAGS="-fkmsrjlpn -i 3/6 'Python integration tests for pants - shard
        4'", CI_FLAGS="-fkmsrjlpn -i 4/6 'Python integration tests for pants - shard
        5'", CI_FLAGS="-fkmsrjlpn -i 5/6 'Python integration tests for pants - shard
        6'"]}, install: [pip --quiet install coveralls], language: python, python: [
    2.7.11], script: 'uname -a

    java -version

    ./build-support/bin/ci.sh -x ${CI_FLAGS}

    ', sudo: required}
